import { appRoutes } from "@/lib/routes";
import type { ProductTourStep } from "@/modules/product-tour/product-tour-types";

export const PRODUCT_TOUR_STEPS: ProductTourStep[] = [
  {
    id: "dashboard_summary",
    route: appRoutes.dashboard,
    target: "dashboard-summary",
    title: "Resumo financeiro",
    description: "Este bloco resume saldo, entradas e saidas logo na chegada ao dashboard.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "dashboard_transactions",
    route: appRoutes.dashboard,
    target: "dashboard-transactions",
    title: "Transacoes recentes",
    description: "Aqui voce valida rapidamente as ultimas movimentacoes sem sair da tela inicial.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "dashboard_insights",
    route: appRoutes.dashboard,
    target: "dashboard-insights",
    title: "Insights do dashboard",
    description: "Os insights apontam padroes, desvios e oportunidades de ajuste com base nos seus dados.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "dashboard_accounts",
    route: appRoutes.dashboard,
    target: "dashboard-banks",
    title: "Contas conectadas",
    description: "Esta area mostra suas contas, cartoes e saldo por origem para facilitar a leitura do caixa.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "accounts_summary",
    route: appRoutes.accounts,
    target: "accounts-summary",
    title: "Resumo de contas",
    description: "Os cards iniciais mostram rapidamente quantas contas bancarias, cartoes e caixas voce tem.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "accounts_structure",
    route: appRoutes.accounts,
    target: "accounts-structure",
    title: "Estrutura financeira",
    description: "Aqui voce organiza contas, revisa cartoes vinculados e acompanha a hierarquia da sua estrutura.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "accounts_support",
    route: appRoutes.accounts,
    target: "accounts-support",
    title: "Painel lateral",
    description: "Este card lateral complementa a leitura da pagina e pode receber orientacoes e proximas acoes.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "transactions_filters",
    route: appRoutes.transactions,
    target: "transactions-filters",
    title: "Filtros de transacoes",
    description: "Use estes filtros para recortar periodo, categoria, busca e tipo antes de analisar os dados.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "transactions_summary",
    route: appRoutes.transactions,
    target: "transactions-summary",
    title: "Resumo filtrado",
    description: "Os cards resumem receitas, despesas e saldo considerando somente o recorte atual.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "transactions_table",
    route: appRoutes.transactions,
    target: "transactions-table",
    title: "Tabela de transacoes",
    description: "Aqui voce revisa cada lancamento, importa arquivos e cria novas movimentacoes.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "transactions_categories",
    route: appRoutes.transactions,
    target: "transactions-categories",
    title: "Categorias",
    description: "Este painel ajuda a entender o peso de cada categoria e ajustar a classificacao rapidamente.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "recurring_income_filters",
    route: appRoutes.expenseManagementRecurringIncome,
    target: "recurring-income-filters",
    title: "Filtros de receitas recorrentes",
    description: "Comece por aqui para definir periodo, conta e categoria das entradas previsiveis.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "recurring_income_summary",
    route: appRoutes.expenseManagementRecurringIncome,
    target: "recurring-income-summary",
    title: "Resumo das recorrencias",
    description: "Os cards mostram volume, series ativas, media e proximas ocorrencias das receitas recorrentes.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "recurring_income_chart",
    route: appRoutes.expenseManagementRecurringIncome,
    target: "recurring-income-chart",
    title: "Analise visual",
    description: "Este bloco combina grafico e distribuicao para revelar onde as receitas recorrentes se concentram.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "recurring_income_table",
    route: appRoutes.expenseManagementRecurringIncome,
    target: "recurring-income-table",
    title: "Tabela de recorrencias",
    description: "A tabela detalha cada serie e permite editar ou remover ocorrencias do periodo.",
    placement: "top",
    autoScroll: true,
  },
  {
    id: "installments_summary",
    route: appRoutes.expenseManagementInstallments,
    target: "installments-summary",
    title: "Resumo de parcelamentos",
    description: "Os cards iniciais consolidam compromissos futuros e exposicao atual dos parcelamentos.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "installments_filters",
    route: appRoutes.expenseManagementInstallments,
    target: "installments-filters",
    title: "Filtros de parcelamentos",
    description: "Ajuste periodo, conta, categoria e status para focar apenas nos parcelamentos relevantes.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "installments_insights",
    route: appRoutes.expenseManagementInstallments,
    target: "installments-insights",
    title: "Insights e projecoes",
    description: "Estas secoes ajudam a antecipar vencimentos, pressao futura e comportamento das compras parceladas.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "installments_table",
    route: appRoutes.expenseManagementInstallments,
    target: "installments-table",
    title: "Tabela de parcelamentos",
    description: "Aqui voce revisa cada parcela planejada e exporta os dados quando necessario.",
    placement: "top",
    autoScroll: true,
  },
  {
    id: "housing_filters",
    route: appRoutes.expenseManagementHousing,
    target: "housing-filters",
    title: "Filtros de habitacao",
    description: "Use o topo da tela para recortar despesas da casa por periodo, conta, tipo e busca.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "housing_summary",
    route: appRoutes.expenseManagementHousing,
    target: "housing-summary",
    title: "Resumo da habitacao",
    description: "Os cards resumem compromisso do periodo, series ativas, media por vencimento e proximo compromisso.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "housing_trend",
    route: appRoutes.expenseManagementHousing,
    target: "housing-trend",
    title: "Evolucao e distribuicao",
    description: "Este bloco mostra a tendencia das despesas e como os tipos de custo se distribuem.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "housing_table",
    route: appRoutes.expenseManagementHousing,
    target: "housing-table",
    title: "Tabela de despesas recorrentes",
    description: "Aqui voce gerencia as series de habitacao e revisa as cobrancas previstas.",
    placement: "top",
    autoScroll: true,
  },
  {
    id: "expense_metrics_filters",
    route: appRoutes.expenseManagementMetrics,
    target: "expense-metrics-filters",
    title: "Filtros das metricas",
    description: "Defina o recorte de periodo, conta e tipo antes de comparar tendencias e concentracoes.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "expense_metrics_summary",
    route: appRoutes.expenseManagementMetrics,
    target: "expense-metrics-summary",
    title: "Resumo operacional",
    description: "Os cards sintetizam despesas, saldo, ticket medio e dias com movimentacao no recorte.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "expense_metrics_trend",
    route: appRoutes.expenseManagementMetrics,
    target: "expense-metrics-trend",
    title: "Tendencia e categorias",
    description: "Este bloco cruza tendencia temporal com concentracao por categoria para destacar pressao de gastos.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "expense_metrics_ranking",
    route: appRoutes.expenseManagementMetrics,
    target: "expense-metrics-ranking",
    title: "Rankings e leituras rapidas",
    description: "Aqui voce entende quais contas e categorias mais pressionam seu resultado.",
    placement: "top",
    autoScroll: true,
  },
  {
    id: "insights_summary",
    route: appRoutes.insights,
    target: "insights-summary",
    title: "Resumo dos insights",
    description: "Os cards superiores mostram volume de insights e a categoria que mais pesa no periodo.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "insights_recommendations",
    route: appRoutes.insights,
    target: "insights-recommendations",
    title: "Insights acionaveis",
    description: "Este painel traz leituras automaticas e recomendacoes praticas para agir no produto.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "insights_spending",
    route: appRoutes.insights,
    target: "insights-spending",
    title: "Gasto por categoria",
    description: "Ao lado, voce enxerga o grafico e uma leitura rapida para contextualizar os insights.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "notifications_filters",
    route: appRoutes.notifications,
    target: "notifications-filters",
    title: "Filtros de notificacoes",
    description: "Ajuste status, origem e periodo para revisar somente os alertas importantes agora.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "notifications_inbox",
    route: appRoutes.notifications,
    target: "notifications-inbox",
    title: "Caixa de entrada",
    description: "Aqui ficam os alertas recebidos, com destaque para leitura rapida e status.",
    placement: "right",
    autoScroll: true,
  },
  {
    id: "notifications_details",
    route: appRoutes.notifications,
    target: "notifications-details",
    title: "Detalhes da notificacao",
    description: "Ao selecionar um item, este painel mostra o contexto completo e as acoes disponiveis.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "notifications_form",
    route: appRoutes.notifications,
    target: "notifications-form",
    title: "Novo lembrete",
    description: "Use este formulario para criar lembretes pessoais direto dentro da caixa de notificacoes.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "chat_conversation",
    route: appRoutes.chat,
    target: "chat-conversation",
    title: "Conversa com a IA",
    description: "Este painel principal concentra as perguntas e respostas sobre seus dados financeiros.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "chat_suggestions",
    route: appRoutes.chat,
    target: "chat-suggestions",
    title: "Sugestoes de perguntas",
    description: "Aqui voce encontra atalhos para iniciar perguntas uteis sem pensar na formulacao.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "profile_identity",
    route: appRoutes.profile,
    target: "profile-identity",
    title: "Identidade da conta",
    description: "Esta secao resume nome, e-mail, status e plano atual do usuario.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "profile_account",
    route: appRoutes.profile,
    target: "profile-account",
    title: "Conta e tour",
    description: "Aqui voce acompanha o progresso do tour, status do plano e sinais principais da conta.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "profile_shortcuts",
    route: appRoutes.profile,
    target: "profile-shortcuts",
    title: "Atalhos",
    description: "Este painel acelera tarefas frequentes, incluindo reiniciar o tour manualmente.",
    placement: "left",
    autoScroll: true,
  },
  {
    id: "settings_account",
    route: appRoutes.settings,
    target: "settings-account",
    title: "Conta",
    description: "Comece pelas configuracoes principais da conta: nome, e-mail e verificacao.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "settings_security",
    route: appRoutes.settings,
    target: "settings-security",
    title: "Seguranca",
    description: "Esta secao concentra troca de senha, verificacao e acoes sensiveis da sessao.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "settings_contact",
    route: appRoutes.settings,
    target: "settings-contact",
    title: "Perfil e contato",
    description: "Aqui ficam telefone e endereco para manter o cadastro completo e pronto para futuras integracoes.",
    placement: "bottom",
    autoScroll: true,
  },
  {
    id: "settings_preferences",
    route: appRoutes.settings,
    target: "settings-preferences",
    title: "Preferencias",
    description: "Use esta area para ajustar comportamento local do app e notificacoes do dispositivo.",
    placement: "top",
    autoScroll: true,
  },
];
