CREATE TABLE IF NOT EXISTS installment_purchases (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bank_connection_id INTEGER REFERENCES bank_connections(id) ON DELETE SET NULL,
  category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
  seed_key TEXT NOT NULL,
  description_base TEXT NOT NULL,
  normalized_description_base TEXT NOT NULL,
  purchase_occurred_on DATE NOT NULL,
  installment_count INTEGER NOT NULL CHECK (installment_count >= 2),
  amount_per_installment NUMERIC(12, 2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, seed_key)
);

ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS installment_purchase_id INTEGER REFERENCES installment_purchases(id) ON DELETE SET NULL;

ALTER TABLE transactions
  ADD COLUMN IF NOT EXISTS installment_number INTEGER;

CREATE INDEX IF NOT EXISTS idx_installment_purchases_user_purchase_date
ON installment_purchases (user_id, purchase_occurred_on DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_transactions_installment_purchase_number
ON transactions (installment_purchase_id, installment_number)
WHERE installment_purchase_id IS NOT NULL AND installment_number IS NOT NULL;
