CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  source TEXT NOT NULL CHECK (source IN ('user_self', 'admin_all', 'admin_selected')),
  category TEXT NOT NULL CHECK (category IN ('general', 'invoice_due', 'financing_due', 'installment_due', 'housing_due', 'custom')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  trigger_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notification_recipients (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id INTEGER NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (notification_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_notification_recipients_user_created
ON notification_recipients (user_id, created_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_notification_recipients_user_unread
ON notification_recipients (user_id, is_read)
WHERE is_read = FALSE;

CREATE INDEX IF NOT EXISTS idx_notifications_created_by
ON notifications (created_by_user_id, created_at DESC);
