ALTER TABLE plan_items
ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high'));

CREATE TABLE IF NOT EXISTS plan_ai_assessments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('on_track', 'attention', 'at_risk', 'completed')),
  risk_summary TEXT NOT NULL DEFAULT '',
  suggested_priority TEXT NOT NULL DEFAULT 'medium' CHECK (suggested_priority IN ('low', 'medium', 'high')),
  adjustment_recommendation TEXT NOT NULL DEFAULT '',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  assessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_plan_ai_assessments_plan_assessed
ON plan_ai_assessments (plan_id, assessed_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS plan_recommendations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id INTEGER NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  assessment_id INTEGER REFERENCES plan_ai_assessments(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'applied', 'dismissed')),
  title TEXT NOT NULL,
  rationale TEXT NOT NULL DEFAULT '',
  proposed_plan JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  applied_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_plan_recommendations_plan_status
ON plan_recommendations (plan_id, status, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS plan_chat_summaries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id INTEGER NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  summary TEXT NOT NULL,
  message_count INTEGER NOT NULL DEFAULT 0,
  last_message_id INTEGER,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (chat_id)
);

CREATE INDEX IF NOT EXISTS idx_plan_chat_summaries_user_updated
ON plan_chat_summaries (user_id, updated_at DESC);

ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS plan_id INTEGER REFERENCES plans(id) ON DELETE SET NULL;

ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS plan_alert_type TEXT;

ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS plan_alert_window_start TIMESTAMPTZ;

ALTER TABLE notifications
ADD COLUMN IF NOT EXISTS action_href TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_plan_alert_dedupe
ON notifications (created_by_user_id, plan_id, plan_alert_type, plan_alert_window_start)
WHERE plan_id IS NOT NULL AND plan_alert_type IS NOT NULL AND plan_alert_window_start IS NOT NULL;
