CREATE TABLE IF NOT EXISTS plan_ai_drafts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  chat_id INTEGER NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
  assistant_message_id INTEGER REFERENCES chat_messages(id) ON DELETE SET NULL,
  public_id TEXT NOT NULL UNIQUE,
  draft JSONB NOT NULL DEFAULT '{}'::jsonb,
  revision_messages JSONB NOT NULL DEFAULT '[]'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'dismissed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_plan_ai_drafts_assistant_message
ON plan_ai_drafts (assistant_message_id)
WHERE assistant_message_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_plan_ai_drafts_one_pending_per_chat
ON plan_ai_drafts (user_id, chat_id)
WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_plan_ai_drafts_user_public
ON plan_ai_drafts (user_id, public_id);
