-- Migration: Pluggy Open Finance integration (premium feature)
-- Uses Pluggy Connect Widget flow: no per-user access tokens.
-- App-level CLIENT_ID + CLIENT_SECRET generate a short-lived API key on demand.
-- We store only the Pluggy Item ID per user connection.

-- One Pluggy item (bank connection) per user
CREATE TABLE IF NOT EXISTS pluggy_connections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pluggy_item_id TEXT NOT NULL,
  last_sync_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id)
);

-- Link each bank_connection row to its Pluggy account ID and parent connection
ALTER TABLE bank_connections
  ADD COLUMN IF NOT EXISTS pluggy_connection_id INTEGER REFERENCES pluggy_connections(id) ON DELETE SET NULL;

ALTER TABLE bank_connections
  ADD COLUMN IF NOT EXISTS pluggy_account_id TEXT;

-- Unique constraint so ON CONFLICT works in upsert
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'bank_connections_user_pluggy_account_unique'
  ) THEN
    ALTER TABLE bank_connections
      ADD CONSTRAINT bank_connections_user_pluggy_account_unique UNIQUE (user_id, pluggy_account_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pluggy_connections_user ON pluggy_connections(user_id);
CREATE INDEX IF NOT EXISTS idx_bank_connections_pluggy ON bank_connections(pluggy_connection_id);
CREATE INDEX IF NOT EXISTS idx_bank_connections_pluggy_account ON bank_connections(pluggy_account_id);
