-- Migration: Add Pluggy columns to bank_connections that were skipped when
-- migration 031 was already marked as applied but the table already existed.

-- Ensure pluggy_connections exists with correct schema (no access_token)
CREATE TABLE IF NOT EXISTS pluggy_connections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  pluggy_item_id TEXT NOT NULL,
  last_sync_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id)
);

-- Remove legacy OAuth columns if they somehow still exist
ALTER TABLE pluggy_connections DROP COLUMN IF EXISTS access_token;
ALTER TABLE pluggy_connections DROP COLUMN IF EXISTS refresh_token;
ALTER TABLE pluggy_connections DROP COLUMN IF EXISTS token_expires_at;

-- Add Pluggy columns to bank_connections
ALTER TABLE bank_connections
  ADD COLUMN IF NOT EXISTS pluggy_connection_id INTEGER REFERENCES pluggy_connections(id) ON DELETE SET NULL;

ALTER TABLE bank_connections
  ADD COLUMN IF NOT EXISTS pluggy_account_id TEXT;

-- Unique constraint for upsert ON CONFLICT
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'bank_connections_user_pluggy_account_unique'
  ) THEN
    ALTER TABLE bank_connections
      ADD CONSTRAINT bank_connections_user_pluggy_account_unique UNIQUE (user_id, pluggy_account_id);
  END IF;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_pluggy_connections_user ON pluggy_connections(user_id);
CREATE INDEX IF NOT EXISTS idx_bank_connections_pluggy ON bank_connections(pluggy_connection_id);
CREATE INDEX IF NOT EXISTS idx_bank_connections_pluggy_account ON bank_connections(pluggy_account_id);
