ALTER TABLE bank_connections
ADD COLUMN IF NOT EXISTS notify_invoice_closed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE bank_connections
ADD COLUMN IF NOT EXISTS notify_invoice_due_soon BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE bank_connections
ADD COLUMN IF NOT EXISTS invoice_due_reminder_days INTEGER NOT NULL DEFAULT 3;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'bank_connections_invoice_due_reminder_days_check'
  ) THEN
    ALTER TABLE bank_connections
    ADD CONSTRAINT bank_connections_invoice_due_reminder_days_check
    CHECK (invoice_due_reminder_days BETWEEN 1 AND 15);
  END IF;
END $$;

ALTER TABLE notifications
DROP CONSTRAINT IF EXISTS notifications_source_check;

ALTER TABLE notifications
ADD CONSTRAINT notifications_source_check
CHECK (source IN ('user_self', 'admin_all', 'admin_selected', 'system'));

CREATE TABLE IF NOT EXISTS invoice_notification_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bank_connection_id INTEGER NOT NULL REFERENCES bank_connections(id) ON DELETE CASCADE,
  invoice_period_end DATE NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('invoice_closed', 'invoice_due_soon')),
  notification_id INTEGER REFERENCES notifications(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, bank_connection_id, invoice_period_end, event_type)
);

CREATE INDEX IF NOT EXISTS idx_invoice_notification_events_user_card
ON invoice_notification_events (user_id, bank_connection_id, invoice_period_end DESC);
